version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Running pre-build steps...
      - python3 -m venv .venv
      - source .venv/bin/activate
      - pip install --upgrade pip

  build:
    commands:
      - echo Running build steps...
      - echo Packaging application...

  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - app-package.zip
    - "**/*"
